# Generated by Django 5.2.4 on 2025-07-14 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('mol', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('passport', models.FileField(blank=True, null=True, upload_to='documents/passports/')),
                ('visa', models.FileField(blank=True, null=True, upload_to='documents/visas/')),
                ('labour_card', models.FileField(blank=True, null=True, upload_to='documents/labour_cards/')),
                ('eid', models.FileField(blank=True, null=True, upload_to='documents/eids/')),
                ('passport_status', models.CharField(default='With company', max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('eid_number', models.CharField(blank=True, max_length=20, null=True)),
                ('labour_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('labour_card_expiry', models.DateField(blank=True, null=True)),
                ('eid_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
