# Generated by Django 5.2.3 on 2025-07-15 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_employee_status_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='mol',
        ),
    ]
