# Generated by Django 5.2.3 on 2025-07-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_employee_mol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mol', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
