# Generated by Django 5.2.3 on 2025-07-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_mol'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.mol'),
        ),
    ]
