# Generated by Django 5.2.3 on 2025-07-15 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_mol'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_from', models.DateField()),
                ('expected_to', models.DateField()),
                ('reported_to', models.CharField(max_length=100)),
                ('actual_from', models.DateField(blank=True, null=True)),
                ('actual_to', models.DateField(blank=True, null=True)),
                ('rejoined_on', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.leavetype')),
            ],
            options={
                'ordering': ['-expected_from'],
            },
        ),
    ]
