# Generated by Django 5.2.3 on 2025-07-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_leavetype_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='actual_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
