# Generated by Django 5.2.4 on 2025-07-15 13:21

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_leave_actual_days_leave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
    ]
