# Generated by Django 5.2.4 on 2025-07-19 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='emp_salary',
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.FloatField()),
                ('basic_salary', models.FloatField(blank=True, null=True)),
                ('hra', models.FloatField(blank=True, null=True)),
                ('other_allowances', models.FloatField(blank=True, null=True)),
                ('transport_allowance', models.FloatField(blank=True, null=True)),
                ('deducted_chargers', models.FloatField(blank=True, default=0.0, null=True)),
                ('leave_deduction', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
