# Generated by Django 5.2.4 on 2025-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_leave_approved_by_leave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Head', 'Head'), ('Employee', 'Employee')], max_length=20, unique=True)),
            ],
        ),
    ]
