# Generated by Django 5.2.4 on 2025-09-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_role_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_application',
            field=models.FileField(blank=True, null=True, upload_to='leave_applications/'),
        ),
    ]
