# Generated by Django 5.2.3 on 2026-06-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_employee_user_dept_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Head_Approved', 'Head Approved'), ('MD_Approved', 'MD Approved'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('Head', 'Head'), ('MD', 'MD'), ('HR', 'HR')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
