# Generated by Django 5.2.3 on 2026-06-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_remove_salary_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/driving_licenses/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance',
            field=models.FileField(blank=True, null=True, upload_to='documents/insurance/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
