# Generated by Django 5.2.4 on 2026-06-27 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_salary_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.FloatField(default=0)),
                ('hra', models.FloatField(default=0)),
                ('transport', models.FloatField(default=0)),
                ('others', models.FloatField(default=0)),
                ('bonus', models.FloatField(default=0)),
                ('overtime_pay', models.FloatField(default=0)),
                ('other_additions', models.FloatField(default=0)),
                ('loan_deduction', models.FloatField(default=0)),
                ('other_deductions', models.FloatField(default=0)),
                ('gross_salary', models.FloatField(default=0)),
                ('net_salary', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hr.payrollrun')),
            ],
            options={
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
