# Generated by Django 5.2.3 on 2026-07-01 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_employee_photo_alter_advancedeductionchange_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('Increment', 'Increment'), ('Decrement', 'Decrement'), ('Adjustment', 'Adjustment')], max_length=20)),
                ('effective_date', models.DateField()),
                ('old_salary', models.FloatField(blank=True, null=True)),
                ('old_basic', models.FloatField(default=0)),
                ('old_hra', models.FloatField(default=0)),
                ('old_transport', models.FloatField(default=0)),
                ('old_others', models.FloatField(default=0)),
                ('new_salary', models.FloatField()),
                ('new_basic', models.FloatField(default=0)),
                ('new_hra', models.FloatField(default=0)),
                ('new_transport', models.FloatField(default=0)),
                ('new_others', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_revisions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_revisions', to='hr.employee')),
            ],
            options={
                'ordering': ['-effective_date', '-changed_at'],
            },
        ),
    ]
