# Generated by Django 5.2.3 on 2026-07-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0032_notification_expiry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mol',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mol',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='mol_documents/licenses/'),
        ),
        migrations.AddField(
            model_name='mol',
            name='tenancy_contract',
            field=models.FileField(blank=True, null=True, upload_to='mol_documents/tenancy/'),
        ),
        migrations.AddField(
            model_name='mol',
            name='tenancy_contract_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mol',
            name='trade_license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mol',
            name='trade_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='mol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hr.mol'),
        ),
    ]
