# Generated by Django 5.2.3 on 2026-07-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_mol_document_fields_and_notification_mol'),
    ]

    operations = [
        migrations.AddField(
            model_name='mol',
            name='establishment_card',
            field=models.FileField(blank=True, null=True, upload_to='mol_documents/establishment/'),
        ),
        migrations.AddField(
            model_name='mol',
            name='establishment_card_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
