# Generated by Django 5.2.3 on 2026-07-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0035_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='attendance_deduction',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='half_days',
            field=models.IntegerField(default=0),
        ),
    ]
