# Generated by Django 5.2.4 on 2026-07-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0038_employee_bank_account_number_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='routing_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
