# Generated by Django 5.2.4 on 2026-07-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0039_employee_routing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='visa_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='fuel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salaryrevision',
            name='new_fuel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salaryrevision',
            name='old_fuel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='fuel',
            field=models.FloatField(default=0),
        ),
    ]
