# Generated by Django 5.2.4 on 2026-07-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0040_employee_visa_number_payrollentry_fuel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bank_account_number',
        ),
    ]
