# Generated by Django 5.2.4 on 2026-07-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0041_remove_employee_bank_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mol',
            name='company_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mol',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='mol',
            name='wps_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
