# Generated by Django 5.2.4 on 2026-07-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0042_mol_company_code_mol_iban_mol_wps_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('self', 'Self check-in'), ('hr', 'HR entry'), ('head', 'Head entry'), ('leave_auto', 'Approved leave')], default='hr', max_length=20),
        ),
    ]
