# Generated by Django 5.2.4 on 2026-07-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0045_monthlyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='labour_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
