# Generated by Django 5.2.3 on 2026-07-03 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0047_weeklyreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(choices=[('Company', 'Company Vehicle'), ('Personal', 'Personal Vehicle')], default='Company', max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('car_number', models.CharField(max_length=50, verbose_name='Car Number')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='Model')),
                ('tracking', models.CharField(blank=True, default='', max_length=100, verbose_name='Tracking')),
                ('tracking_exp_date', models.DateField(blank=True, null=True, verbose_name='Tracking Exp Date')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='State')),
                ('traffic_code', models.CharField(blank=True, default='', max_length=100, verbose_name='Traffic Code')),
                ('mortgage', models.CharField(blank=True, default='', max_length=150, verbose_name='Mortgage')),
                ('car_and_model', models.CharField(blank=True, default='', max_length=200, verbose_name='Car and Model')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='Company')),
                ('mulkiya_expiry', models.DateField(blank=True, null=True, verbose_name='Mulkiya Expiry')),
                ('mulkiya_document', models.FileField(blank=True, null=True, upload_to='vehicles/mulkiya/', verbose_name='Mulkiya Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
