# Generated by Django 5.2.3 on 2026-07-03 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0048_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='hr.employee'),
        ),
    ]
