# Generated by Django 5.2.3 on 2026-07-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0049_vehicle_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hr.vehicle'),
        ),
    ]
