# Generated by Django 5.2.3 on 2026-07-10 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0051_vehicleservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleservice',
            name='cost_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleservice',
            name='cost_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleservice',
            name='cost_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_approved_vehicle_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
