# Generated by Django 5.2.3 on 2026-07-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0052_vehicleservice_cost_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherrecord',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('visa', 'Visa Expense'), ('vehicle', 'Vehicle'), ('office', 'Office'), ('marketing', 'Marketing'), ('it', 'IT'), ('general', 'General'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='otherrecord',
            name='expense_other',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Other expense (specify)'),
        ),
    ]
