# Generated by Django 5.2.3 on 2026-07-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0053_otherrecord_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sold_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sold Amount'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sold_document',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/sold/', verbose_name='Sale Document'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sold_on',
            field=models.DateField(blank=True, null=True, verbose_name='Sold On'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sold_to',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Sold To'),
        ),
    ]
