# Generated by Django 5.2.3 on 2026-07-10 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0054_vehicle_is_sold_vehicle_sold_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('self', 'Management'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('other', 'Other')], default='self', max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('designation', models.CharField(blank=True, default='', max_length=150, verbose_name='Designation / Role')),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='management/photos/')),
                ('eid_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Emirates ID Number')),
                ('eid_expiry', models.DateField(blank=True, null=True, verbose_name='Emirates ID Expiry')),
                ('eid_document', models.FileField(blank=True, null=True, upload_to='management/eid/', verbose_name='Emirates ID Document')),
                ('passport_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Passport Number')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='Passport Expiry')),
                ('passport_document', models.FileField(blank=True, null=True, upload_to='management/passport/', verbose_name='Passport Document')),
                ('dl_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Driving License Number')),
                ('dl_expiry', models.DateField(blank=True, null=True, verbose_name='Driving License Expiry')),
                ('dl_document', models.FileField(blank=True, null=True, upload_to='management/dl/', verbose_name='Driving License Document')),
                ('visa_type', models.CharField(blank=True, choices=[('employment', 'Employment Visa'), ('residence', 'Residence Visa'), ('investor', 'Investor Visa'), ('partner', 'Partner Visa'), ('golden', 'Golden Visa'), ('green', 'Green Visa'), ('family', 'Family / Dependent Visa'), ('visit', 'Visit Visa'), ('tourist', 'Tourist Visa'), ('mission', 'Mission Visa'), ('student', 'Student Visa'), ('retirement', 'Retirement Visa'), ('other', 'Other')], default='', max_length=20, verbose_name='Visa Type')),
                ('visa_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Visa Number')),
                ('visa_expiry', models.DateField(blank=True, null=True, verbose_name='Visa Expiry')),
                ('visa_document', models.FileField(blank=True, null=True, upload_to='management/visa/', verbose_name='Visa Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_management', to=settings.AUTH_USER_MODEL)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='hr.managementmember')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=150)),
                ('purpose', models.CharField(blank=True, default='', max_length=200)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('document', models.FileField(blank=True, null=True, upload_to='management/travel/', verbose_name='Travel Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_travels', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='hr.managementmember')),
            ],
            options={
                'ordering': ['-departure_date', '-created_at'],
            },
        ),
    ]
