# Generated by Django 5.2.3 on 2026-07-10 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0055_managementmember_travelrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('visa_type', models.CharField(blank=True, choices=[('tourist', 'Tourist'), ('visit', 'Visit'), ('business', 'Business'), ('work', 'Work'), ('student', 'Student'), ('residence', 'Residence'), ('transit', 'Transit'), ('other', 'Other')], default='', max_length=20, verbose_name='Visa Type')),
                ('number', models.CharField(blank=True, default='', max_length=50, verbose_name='Visa Number')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='Expiry')),
                ('document', models.FileField(blank=True, null=True, upload_to='management/country_visa/', verbose_name='Visa Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_country_visas', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_visas', to='hr.managementmember')),
            ],
            options={
                'ordering': ['country', '-expiry'],
            },
        ),
    ]
