# Generated by Django 5.2.3 on 2026-07-10 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0057_notification_management_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Property Name')),
                ('category', models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('phone', 'Phone'), ('sim', 'SIM Card'), ('tablet', 'Tablet'), ('furniture', 'Furniture'), ('equipment', 'Equipment'), ('tool', 'Tool'), ('other', 'Other')], default='', max_length=20)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Serial / Asset No.')),
                ('description', models.TextField(blank=True, default='')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Value (AED)')),
                ('document', models.FileField(blank=True, null=True, upload_to='properties/', verbose_name='Document')),
                ('assigned_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='hr.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company properties',
                'ordering': ['name'],
            },
        ),
    ]
