# Generated by Django 5.2.3 on 2026-07-10 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0058_companyproperty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_type', models.CharField(choices=[('holiday', 'National Holiday Declaration'), ('warning_employee', 'Warning to Employee'), ('warning_department', 'Warning to Department'), ('general', 'General Memo to All Staff')], default='general', max_length=25)),
                ('ref_no', models.CharField(blank=True, default='', max_length=60, verbose_name='Reference No.')),
                ('to_text', models.CharField(default='All Staff', max_length=200, verbose_name='To')),
                ('memo_date', models.DateField()),
                ('subject', models.CharField(max_length=300, verbose_name='Subject (Re)')),
                ('body', models.TextField()),
                ('signatory', models.CharField(default='HR/ADMIN DIVISION', max_length=120)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='memos/signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memos', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos', to='hr.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos', to='hr.employee')),
            ],
            options={
                'ordering': ['-memo_date', '-created_at'],
            },
        ),
    ]
