# Generated by Django 5.2.4 on 2026-07-14 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0062_vehicleodometerreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leaves', to='hr.employee'),
        ),
    ]
