# Generated by Django 5.2.3 on 2026-07-20 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0065_salarycertificaterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourCardRenewalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_snapshot', models.DateField()),
                ('whatsapp_status', models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_sent', max_length=10)),
                ('whatsapp_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('whatsapp_error', models.TextField(blank=True, default='')),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_to_number', models.CharField(blank=True, default='', max_length=30)),
                ('response', models.CharField(blank=True, choices=[('', 'Awaiting Response'), ('Yes', 'Yes — Renew'), ('No', 'No — Do Not Renew')], default='', max_length=5)),
                ('response_raw', models.CharField(blank=True, default='', max_length=255)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_renewal_prompts', to='hr.employee')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_labour_renewal_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'expiry_snapshot')},
            },
        ),
    ]
