# Generated by Django 5.2.4 on 2026-07-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0067_propertycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproperty',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('damaged', 'Damaged')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='companyproperty',
            name='status_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sold Amount (AED)'),
        ),
        migrations.AddField(
            model_name='companyproperty',
            name='status_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sold / Damaged On'),
        ),
        migrations.AddField(
            model_name='companyproperty',
            name='status_document',
            field=models.FileField(blank=True, null=True, upload_to='properties/status/', verbose_name='Sale / Damage Document'),
        ),
        migrations.AddField(
            model_name='companyproperty',
            name='status_note',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='companyproperty',
            name='status_party',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Sold To / Reported By'),
        ),
    ]
