"""
Django settings for hr_module project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-wc(r-tw%75p9^1hu!*spg&2p^jfm2q)#s%9fs-15v9g*es8!$x')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# ── WhatsApp Cloud API (Meta) — birthday wishes ──────────────────────────────
# Fill these in via environment / .env once the Meta app + template are ready.
# NB: python-decouple keeps trailing inline "# comments" as part of the value,
# so these helpers strip them defensively (a value with a real '#' is unaffected
# for tokens/ids/codes, which never contain one).
def _env_str(key, default=''):
    return str(config(key, default=default)).split(' #', 1)[0].split('\t#', 1)[0].strip()

def _env_bool(key, default):
    raw = str(config(key, default=str(default))).split('#', 1)[0].strip().lower()
    return raw in ('1', 'true', 'yes', 'on')

WHATSAPP_ACCESS_TOKEN         = _env_str('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID      = _env_str('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_API_VERSION          = _env_str('WHATSAPP_API_VERSION', 'v21.0')
# The approved message template name + its language code, as created in Meta.
WHATSAPP_BIRTHDAY_TEMPLATE      = _env_str('WHATSAPP_BIRTHDAY_TEMPLATE', 'birthday_wish')
WHATSAPP_BIRTHDAY_TEMPLATE_LANG = _env_str('WHATSAPP_BIRTHDAY_TEMPLATE_LANG', 'en')
# If your template has a {{1}} body variable, we pass the employee's first name.
# Set to False if your template takes no variables.
WHATSAPP_BIRTHDAY_NAME_PARAM  = _env_bool('WHATSAPP_BIRTHDAY_NAME_PARAM', True)
# Default country code prepended to local numbers (UAE = 971).
WHATSAPP_DEFAULT_COUNTRY_CODE = _env_str('WHATSAPP_DEFAULT_COUNTRY_CODE', '971')

# ── Logging — self-rotating birthday-wish log (no cron cleanup needed) ────────
# Writes to logs/birthday_wishes.log and rotates at ~1 MB, keeping 1 backup, so
# the whole thing never exceeds 2 files / ~2 MB on disk.
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'birthday': {
            'format': '%(asctime)s [%(levelname)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'birthday_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'birthday_wishes.log'),
            'maxBytes': 1_000_000,   # ~1 MB per file
            'backupCount': 1,        # keep 1 old file -> 2 files max
            'encoding': 'utf-8',
            'formatter': 'birthday',
        },
    },
    'loggers': {
        'hr.birthday': {
            'handlers': ['birthday_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hr',
    'django_countries'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hr_module.urls'
LOGIN_URL = '/login/'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hr.context_processors.notification_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'hr_module.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Set USE_SQLITE=True in .env for local development, False for production (PostgreSQL).

USE_SQLITE = config('USE_SQLITE', default=True, cast=bool)

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
import os
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@example.com'


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your_app_password'